### PR TITLE
update nsp module to v2.0.0

### PR DESCRIPTION
**Pull request by wei-lee**
Looks like the nsp server is updated and the current 1.1.x version is not working anymore. Need to update to 2.0.0.

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@wei-lee ironically, the build failed here due to a vulnerability found by NSP :trollface:

**Comment by kpiwko** [comment]
Catch 22? No we have no merge without check pass policy here? ;-)

**Comment by grdryn** [comment]
I think maybe we should remove enforcing of nsp from the fh:dist task, what do you all think? Otherwise we can't proceed here (there's no invulnerable version of uglifyjs). It would be better run as the regular time-based check that we've discussed before.

**Comment by fh-automatron** [comment]
@grdryn @jasonmadigan please review this PR.

**Comment by jasonmadigan** [comment]
LGTM. We can run Adam's NSP checks periodically on bob or somewhere instead anyway - will give us better insight into vulnerabilities into deployed software (as opposed to just checking at build-time).

**Pull request merged**
