### PR TITLE
Shrinkwrap updated

### PR DESCRIPTION
**Pull request by lgriffin**
@wtrocki please review this shrinkwrap update

### CODE REVIEW

**Comment by fh-automatron** [comment]
@grdryn @jasonmadigan please review this PR.

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:
- A component owner should review your change (we've tagged these above)
- This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
- Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
- Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
- There should be an associated fhcap PR with this change - please provide a link to this

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by lgriffin** [comment]
Closing -- used the wrong version of npm.

**Comment by grdryn** [comment]
Not sure if a shrinkwrap is actually needed here, is it? @vibe13 is the shrinkwrap file here important for you?

**Comment by wtrocki** [comment]
@lgriffin Just update commit and force-push it to Your local branch. PR will be updated automatically.
@grdryn Do you mean to remove this file?

**Comment by wtrocki** [comment]
Retest this please

**Comment by wtrocki** [comment]
@vibe13 I agree with @grdryn - We may not need shrinkwrap for that file. I'm closing this PR for now. Feel free to reopen it if needed.

**Comment by grdryn** [comment]
I guess @vibe13 will be back on Thursday. @wtrocki note that his workflow is different than our development one, and he has productization processes & scripts that depend on shrinkwrap files for production stuff. I'm not sure about this grunt-fh-build though, since it's a build-time dependency. We can easily add it back if necessary anyway.

**Pull request closed without merging**
